spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    cache: false

  mail:
    username: 904096333@qq.com
    password: qsdsypfdasffbbej
    host: smtp.qq.com
    # qq需要配置ssl
    properties:
      mail:
        smtp:
          ssl:
            enable: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hzc.demo.pojo
  configuration:
    map-underscore-to-camel-case: true

